[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  base = "."


[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 